apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-db-configmap
data:
  POSTGRES_DB: {{ .Values.configmap.dbname }}
  POSTGRES_HOST_AUTH_METHOD: {{ .Values.configmap.hostAuthMethod }}
