apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-db
    spec:
      containers:
      - name: {{ .Chart.Name }}-db
        image: "{{ .Values.imagedb.repository }}:{{ .Values.imagedb.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.imagedb.imagePullPolicy }}
        envFrom:
        - secretRef:
            name: {{ .Chart.Name }}-db-secret
        - configMapRef:
            name: {{ .Chart.Name }}-db-configmap
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: {{ .Chart.Name }}-db-storage
          mountPath: /var/lib/postgresql/data/
      volumes:
      - name: {{ .Chart.Name }}-db-storage
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-db-pvc
