{{- if and .Values.persistencedb.enabled (not .Values.persistencedb.existingClaim) }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-db-pvc
spec:
  storageClassName: {{ .Values.persistencedb.storageClassName | default "local-path" }}
  accessModes:
    - {{ .Values.persistencedb.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.persistencedb.size | default "1Gi" }}
{{ end }}
