apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  DATABASE_URI: {{ default "" .Values.secret.databaseUri | b64enc | quote }}
  CAST_SERVICE_HOST_URL : {{ default "" .Values.secret.castServiceUrl | b64enc | quote }}

