apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-db-secret
type: Opaque
data:
  POSTGRES_PASSWORD: {{ default "" .Values.secretdb.password | b64enc | quote }}
  POSTGRES_USER: {{ default "" .Values.secretdb.username | b64enc | quote }}

