apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-db
spec:
  type: {{ .Values.servicedb.type }}
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}-db
  ports:
  - port: {{ .Values.servicedb.port }}
    targetPort: {{ .Values.servicedb.targetPort }}
