
replicaCount: 2

# informtion pour le service
image:
  repository: dahansop/jenkinsexam-cast
  tag: V26.0
  imagePullPolicy: IfNotPresent

secret:
  databaseuri: "postgresql://admin:password@cast-db:5432/castdb"

service:
  type: ClusterIP
  port: 8000
  targetPort: 8001



# information pour la base de données
imagedb:
  repository: postgres
  tag: 12.1-alpine
  imagePullPolicy: IfNotPresent

persistencedb:
  existingClaim: ""
  enabled: true
  storageClassName: "local-path"
  accessMode: ReadWriteOnce
  size: 1Gi

secretdb:
  username: admin
  password: password

configmap:
  dbname: castdb
  hostAuthMethod: trust

servicedb:
  type: ClusterIP
  port: 5432
  targetPort: 5432


