apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast
  template:
    metadata:
      labels:
        app: cast
    spec:
      containers:
        - name: cast
          image: "dahansop/jenkinsexam-cast:V25.0"
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: cast-secret
          ports:
            - containerPort: 8000
          

