apiVersion: v1
kind: Service
metadata:
  #name: {{ Chart.Name }}
  name: cast-service
  labels:
    #app: {{ .Chart.Name }}
    app: cast
spec:
  #type: {{ .Values.service.type }}
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8001
    #- port: {{ .Values.service.port }}
    #  targetPort: {{ .Values.service.targetPort }}
  selector:
    #app: {{ .Chart.Name }}
    app: cast
